# Generated by Django 4.1 on 2022-09-14 14:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', 'json_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True,
                                              validators=[django.core.validators.MinValueValidator(1)])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_key', models.CharField(editable=False, max_length=10000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='place',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='current_journey_price',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='old_journey_price',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True,
                                      validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='journey',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer',
                                    to='booking.booker'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_flight_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drop_off',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='journey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.journey'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='landing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(
                choices=[('CHILD SEAT', 'Child Seat'), ('INFANT SEAT', 'Infant Seat'), ('WHEELCHAIR', 'Wheelchair'),
                         ('BOOSTER SEAT', 'Booster Seat'), ('EXTRA STOP IN TOWN', 'Extra Stop in Town'),
                         ('SKIS AND SNOWBOARD', 'Ski and Snowboard'), ('BICYCLE', 'Bicycle')], max_length=255),
        ),
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.AddField(
            model_name='equipmentchoice',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.equipmenttype'),
        ),
        migrations.AddField(
            model_name='journey',
            name='equipment_choice',
            field=models.ManyToManyField(to='booking.equipmentchoice'),
        ),
    ]
