# Generated by Django 4.1 on 2022-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', 'json_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
