# Generated by Django 4.1 on 2022-09-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0001_equipmentchoice_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentchoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='old_price',
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(
                choices=[('CHILD SEAT', 'Child Seat'), ('INFANT SEAT', 'Infant Seat'), ('WHEELCHAIR', 'Wheelchair'),
                         ('BOOSTER SEAT', 'Booster Seat'), ('EXTRA STOP IN TOWN', 'Extra Stop in Town'),
                         ('SKIS AND SNOWBOARD', 'Ski and Snowboard'), ('BICYCLE', 'Bicycle')], max_length=255,
                unique=True),
        ),
    ]
