# Generated by Django 4.1 on 2022-09-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_alter_place_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
