# Generated by Django 4.1 on 2022-09-10 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_equipmentchoice_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.equipmentchoice'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='booking.booker'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_flight_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drop_off',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='journey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.journey'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='landing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(null=True),
        ),
    ]
