# Generated by Django 4.1 on 2022-09-08 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='place',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='quantity',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.equipment'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(choices=[('CHILD_SEAT', 'Child Seat'), ('INFANT_SEAT', 'Infant Seat'), ('WHEELCHAIR', 'Wheelchair'), ('BOOSTER_SEAT', 'Booster Seat'), ('EXTRA_STOP_IN_TOWN', 'Extra Stop in Town'), ('SKIS_AND_SNOWBOARD', 'Ski and Snowboard'), ('BICYCLE', 'Bicycle')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='journey',
            name='current_journey_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='old_journey_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, null=True),
        ),
    ]
