# Generated by Django 4.1 on 2022-09-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_equipment_alter_booking_booker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(to='booking.equipmentchoice'),
        ),
    ]
