# Generated by Django 4.1 on 2022-09-16 03:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0003_remove_journey_equipment_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='from_place',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='to_place',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booker',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reference_ID',
        ),
        migrations.RemoveField(
            model_name='equipmentchoice',
            name='session_key',
        ),
        migrations.AddField(
            model_name='booking',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.country'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment_choices',
            field=models.ManyToManyField(to='booking.equipmentchoice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='from_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='journey_from_place', to='booking.place'),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pronoun',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.place'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.vehicle'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_make_and_model',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Booker',
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
    ]
