# Generated by Django 4.1 on 2022-09-09 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_place_remove_equipment_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment',
        ),
        migrations.AddField(
            model_name='journey',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(choices=[('CHILD SEAT', 'Child Seat'), ('INFANT SEAT', 'Infant Seat'), ('WHEELCHAIR', 'Wheelchair'), ('BOOSTER SEAT', 'Booster Seat'), ('EXTRA STOP IN TOWN', 'Extra Stop in Town'), ('SKIS AND SNOWBOARD', 'Ski and Snowboard'), ('BICYCLE', 'Bicycle')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='journey',
            name='current_journey_price',
            field=models.DecimalField(decimal_places=2, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='old_journey_price',
            field=models.DecimalField(decimal_places=2, max_digits=60, null=True),
        ),
    ]
