# Generated by Django 4.1 on 2022-09-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_journey_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment',
        ),
        migrations.AddField(
            model_name='journey',
            name='equipment',
            field=models.ManyToManyField(to='booking.equipmentchoice'),
        ),
    ]
