# Generated by Django 4.1 on 2022-09-17 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0004_remove_journey_from_place_remove_journey_to_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(default='1', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
