# Generated by Django 4.1 on 2022-09-11 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_equipment_journey_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='equipment',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(to='booking.equipmentchoice'),
        ),
        migrations.AddField(
            model_name='equipmentchoice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
