# Generated by Django 4.1 on 2022-09-17 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0005_alter_booking_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.BigIntegerField(default='1', null=True,
                                         validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
