# Generated by Django 4.1 on 2022-09-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_journey_equipment_booking_equipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='equipment',
            new_name='equipment_choice',
        ),
    ]
