# Generated by Django 4.1 on 2022-09-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_equipment_booking_equipment_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentchoice',
            name='price',
        ),
    ]
