# Generated by Django 4.1 on 2022-09-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_passengers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='timestamp',
            new_name='date_filled',
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
