# Generated by Django 4.1 on 2022-09-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_equipmentchoice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment_choice',
        ),
        migrations.AddField(
            model_name='journey',
            name='equipment_choice',
            field=models.ManyToManyField(to='booking.equipmentchoice'),
        ),
    ]
