# Generated by Django 4.1 on 2022-09-11 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_booking_equipment_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentchoice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
