# Generated by Django 4.1 on 2022-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_payment_stripe_token_alter_payment_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
