# Generated by Django 4.1 on 2022-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0011_alter_payment_session_key_alter_payment_stripe_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session_key',
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
