# Generated by Django 4.1 on 2022-10-01 22:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='places'),
        ),
    ]
